version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "sample/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "sample/build.gradle" }}
      - run:
          name: Build APKs
          command: ./gradlew assembleRelease
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: library/build/reports
          destination: library-reports
      - store_artifacts:
          path: sample/build/reports
          destination: sample-reports
      - store_artifacts:
          path: sample/build/outputs/apk/release
          destination: sample-apk
      - store_test_results:
          path: library/build/test-results
      - store_test_results:
          path: sample/build/test-results
